config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end
  devise_for :users, :controllers => { :confirmations => 'devise/confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   root "users#index"
   resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] 
      resources :likes, only: [:create]
  end
end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comments_counter
  def update_comments_counter
    post.increment!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments, dependent: :destroy
  after_create :update_posts_counter
  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_posts_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes
  has_many :comments
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  enum role: { user: 'user', admin: 'admin' }
  def is?(requested_role)
    role == requested_role
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def posts_counter
    update(post_counter: posts.count)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    user = User.find(params[:user_id])
    post = user.posts.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def create
    post = Post.find(params[:post_id])
    User.find(comment_params[:user_id])
    comment = post.comments.new(text: comment_params[:text])
    respond_to do |format|
      if comment.save
        format.json { render json: comment, message: 'Create new comment' }
      else
        format.json { render json: comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :posts_counter)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit({ roles: [] }, :email, :name, :password, :password_confirmation, :current_password)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name, :email)
    end
    devise_parameter_sanitizer.permit(:reset_password) do |user_params|
      user_params.permit(:email, :reset_password_token)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment
      @comment.destroy
      flash[:notice] = 'Comment was deleted'
    else
      flash[:notice] = 'Comment could not be found'
    end
    redirect_to user_posts_path(@post.author)
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.likes.create(post: @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 3)
    @post = @posts.first
    @recent_comment = @post.recent_comments if @post
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
    @name = @user.name if @user
    @text = @post.text
    @posts = @user.posts
    @comments = Comment.where(post_id: @posts.pluck(:id))
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find_by(id: params[:id])
    if @post
      @post.comments.destroy_all
      @post.destroy
      flash[:notice] = 'Post was deleted.'
    else
      flash[:alert] = 'Post could not be found.'
    end
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @bio = @user.bio
    @recent_post = @user.recent_posts
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with(model: [@user, @post, @comment], url: user_post_comments_path(@user, @post), method: :post) do |form| %>
    <%= form.label :text %>
    <%= form.text_area :text %><br>
  
    <%= form.submit "Create Comment" %>
  <% end %>
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like_form.html.erb
<% if user_signed_in? %>
  <div id="like-button" data-post-id="<%= post.id %>" data-likes-count="<%= post.likes.count %>">
    <%= render 'likes/like_button', post: post %>
  </div>
<% else %>
  <%= link_to 'Sign in to like', new_user_session_path %>
<% end %>

app/views/posts/index.html.erb
<div class="user-index">
  <div class='profile'>
    <img src="<%= @user.photo %>" alt="User Photo" />
  </div>
  <div class='name-postnumber'>
    <div><%= @user.name %></div>
    <p class='num-post'>Number of posts: <%= @user.posts.count %></p>
  </div>
</div>

<div class="post-index">
  <div class="post-inner">
    <% if @posts.present? %>
      <% @posts.each_with_index do |post, index| %>
        <%= link_to "Post ##{index + 1}", user_post_path(@user.id, post.id) %>
        <div class="delete-post">
        <% if can? :destroy, @post %>
        <%= form_with url: user_post_path(@post.author, @post), method: :delete do |form| %>
          <%= form.submit 'Delete post', data: { confirm: 'Are you sure?' }, class: "delete-button btn" %>
        <% end %>
      <% end %>
          </div>  

        <p><%= post.text %></p>
        <div class="counter">
          <p><%= "Comments: #{post.comments.count}, " %><%= "Likes: #{pluralize(post.likes.count, 'like')}" %></p>
        </div>
        <section class='comments'>
  <% if post.recent_comments.present? %>
    <% post.recent_comments.each do |comment| %>
      <p><%= comment.user.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment %>
        <%= form_with url: user_post_comment_path(@post.author, @post, comment), method: :delete do |form| %>
          <%= form.submit 'Delete Comment', data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <p>No recent comments.</p>
  <% end %>
</section>
      <% end %>
     
    <% else %>
      <p>No posts available.</p>
    <% end %>
  </div>
</div>
<div class="pagination">
<a href="/"><button type="button"><%= will_paginate %></button></a>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: user_posts_path(@user), method: :post) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :text %>
  <%= form.text_area :text %><br>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<section class="show-post">
  <span>
    <div class="post">Posts <%= @posts.count %> by <%= @name %>
    <div class="delete-post">
    <% if can? :destroy, @post %>
    <%= form_with url: user_post_path(@post.author, @post), method: :delete do |form| %>
      <%= form.submit 'Delete post', data: { confirm: 'Are you sure?' }, class: "delete-button btn" %>
    <% end %>
  <% end %>

      </div>  
    </div>
    <div class="counter">
      
        <button class='comment-button'><%= link_to "Comments: #{@post.comments.count}", new_user_post_comment_path(@user, @post) %></button>
       
        <div class="like-button"><%= form_with url: user_post_likes_path(@post.author.id, @post.id), method: :post do |form| %>
          <%= form.submit "Like #{pluralize(@post.likes.count,'')}" %>
          <% end %>
          </div>   
    </div>
  </span>
  <div><%= @text %></div>
</section>
<section class='comments comment-post'>
  <% if @post.comments.any? %>
    <% @post.comments.each do |comment| %>
      <p><%= comment.user.name %>: <%= comment.text %></p> 
      
      <% if can? :destroy, comment %>
        <%= form_with url: user_post_comment_path(@post.author, @post, comment), method: :delete do |form| %>
          <%= form.submit 'Delete Comment', data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <p>No comments for this post.</p>
  <% end %>
</section>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'style.css' %>
<% @users.each do |user| %>
<div class="user-index">
<div class='profile'><img src="<%= user.photo %>" alt="User Photo"/>
 </div>
<div class='name-postnumber'>
<div> <%= link_to user.name, user_path(user) %>
</div>
<p class='num-post'> number of posts: <%= user.posts.count %></p>       
</div>

</div>
<% end %>

app/views/users/show.html.erb
<div class="user-index">
  <div class='profile'>
    <img src="<%= @user.photo %>" alt="User Photo"/>
  </div>
  <div class='name-postnumber'>
    <div><%= @user.name %></div>
    <div>
    <p class='num-post'>Number of posts: <%= @user.posts.count %></p>
    <button class='createpost-button'><%= link_to "Create post", new_user_post_path(@user) %></button>
</div>
  </div>
 
</div>

<div class='bio'>
  <%= @bio %> <br>
</div>

<div class="post-index">
  <div class="post-inner">
    <% if @recent_post.present? %>
      <% @recent_post.each_with_index do |post, index| %>
        <div>
          <div><%= link_to "Post ##{index + 1}", user_post_path(@user.id, post.id) %><br></div>
          <div>
            <p><%= post.text %></p>
            <div class="counter"> 
              <p><%= "Comments: #{post.comments.count}, " %> <%= "Likes: #{pluralize(post.likes.count, 'like')}" %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No recent posts available.</p>
    <% end %>
  </div>

  <button><%= link_to "See all posts", user_posts_path(@user) %></button>
</div>